### ISSUE TITLE
calibration value differs in each execution

### ISSUE THREAD

**Issue by voyageanp** [ethz-asl/kalibr#126]
I noticed that calibrated value (such as distortion coefficient and translation and rotation) differs every single execution of the kalibr.  I wonder why does that happen. And May I ask what is the key component to stabilize the calibrated value. 
I assume that static data of rosbag and dynamic data of rosbag are used same camera module. And the only difference is that cam2 and cam3 are removed when it's used for imu-camera calibration. Therefore the translation and the rotation between cam0 and cam1 should be the similar between calibrated value by the multiple camera calibration and the value on camchain.yaml in the dynamic dataset. intrinsics are almost same but distortion_coeffs are too different.
So my question is why does the calibration value such as translation and rotation differs in each execution. and even, calibration from static data-set differs from camchain.yaml in dynamic data-set
Best
camchain-static.yaml
```
cam0:
  cam_overlaps: [1, 3]
  camera_model: pinhole
  distortion_coeffs: [0.1647781283144739, -0.8146387117058745, 1.6019447381737542,
    -1.060322992710995]
  distortion_model: equidistant
  intrinsics: [461.8167341624717, 461.1675927559255, 355.2331723876936, 216.5819300448134]
  resolution: [752, 480]
  rostopic: /cam0/image_raw
cam1:
  T_cn_cnm1:
  - [0.9999927798676923, 0.00248220233096194, 0.002877305001026271, -0.11060560257336785]
  - [-0.0024842468775956145, 0.9999966641724566, 0.0007072209031406716, -0.0003656483936269286]
  - [-0.002875539937458723, -0.0007143637328768714, 0.9999956104676264, 0.00016258111373139864]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0, 3]
  camera_model: pinhole
  distortion_coeffs: [-0.19707615099948708, 1.1344672672775424, -2.393057181750592,
    1.6914457427197698]
  distortion_model: equidistant
  intrinsics: [471.7497881614025, 471.15321627233493, 374.2433275201588, 211.8993940656523]
  resolution: [752, 480]
  rostopic: /cam1/image_raw
```
camchain.yaml
```
cam0:
  cam_overlaps: [1, 3]
  camera_model: pinhole
  distortion_coeffs: [-0.0016509958435871643, 0.02437222940989351, -0.03582816956989852,
    0.019860839087717054]
  distortion_model: equidistant
  intrinsics: [461.487246372674, 460.1113992557959, 356.39105303227853, 231.15719697054647]
  resolution: [752, 480]
  rostopic: /cam0/image_raw
cam1:
  T_cn_cnm1:
  - [0.9999987703316401, 0.0011891090293591699, -0.0010224259962834177, -0.11016759824092018]
  - [-0.0011883808160330711, 0.9999990400088897, 0.0007125533866886033, -0.0003216647632433766]
  - [0.0010232723184295653, -0.0007113374790444545, 0.9999992234560721, 0.00012078907255410462]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0, 3]
  camera_model: pinhole
  distortion_coeffs: [-0.0009362378060020789, 0.018833308358932984, -0.030558453797100132,
    0.01955083559432553]
  distortion_model: equidistant
  intrinsics: [462.4318044040118, 461.1780497604126, 377.0119530476368, 226.49966248854923]
  resolution: [752, 480]
  rostopic: /cam1/image_raw
```

Just for clarification, I used the april_6x6_80x80cm_A0.pdf for calibration board at the same scale.
