### ISSUE TITLE
Multi IMU and IMU intrinsic calibration

### ISSUE THREAD

**Issue by AlyonaV** [ethz-asl/kalibr#327]
According to Wiki, kalibr "allows for estimating IMU intrinsics as well as the displacement of the accelerometer y- and z-axis with respect to its x-axis". I run kalibr_calibrate_imu_camera but can`t find out how to get the value of the displacement of the accelerometer y- and z-axis with respect to its x-axis. I suppose that this should be written in the file imu-%BAGNAME%.yaml. But I have just this data:
```
imu0:
  T_i_b:
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.02
  accelerometer_random_walk: 0.002
  gyroscope_noise_density: 0.02
  gyroscope_random_walk: 4.08068016281e-05
  model: calibrated
  rostopic: /imu0
  time_offset: 0.0
  update_rate: 400.0
```

How can I get the the value of the displacement of the accelerometer y- and z-axis with respect to its x-axis?
