### ISSUE TITLE
IMU yaml file

### ISSUE THREAD

**Issue by boeun98** [ethz-asl/kalibr#512]
I did the [](https://github.com/gaowenliang/imu_utils)

But how do I create an IMU yaml file with this output file?

```
%YAML:1.0

---

type: IMU

name: ocams

Gyr:

   unit: " rad/s"

   avg-axis:

      gyr_n: 1.0098123168809940e+00

      gyr_w: 4.8477797168896648e-03

   x-axis:

      gyr_n: 1.9409585648613938e+00

      gyr_w: 4.8477797168896648e-03

   y-axis:

      gyr_n: 4.7935284743547169e-01

      gyr_w: 4.8477797168896648e-03

   z-axis:

      gyr_n: 6.0912553834611671e-01

      gyr_w: 4.8477797168896648e-03

Acc:

   unit: " m/s^2"

   avg-axis:

      acc_n: 4.2231882558139615e+00

      acc_w: 5.1441796693833908e-01

   x-axis:

      acc_n: 2.6251373597056422e+00

      acc_w: 1.7415384839840692e-01

   y-axis:

      acc_n: 8.7076691398096013e+00

      acc_w: 1.0544698798857202e+00

   z-axis:

      acc_n: 1.3367582679266417e+00

      acc_w: 3.1463017253089015e-01
```
